leftnav:
- identifier: 0370554b-18e1-90e6-15e3-5a2b4ad0c204
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: 6de678fd-f542-ae23-9de0-55d7b2f9baa1
  name: Instructor Insights
  url: /pages/instructor-insights
  weight: 20
- identifier: external-4424bee996e14f97945e14cfd55f792e
  name: Online Publication
  url: https://openlearninglibrary.mit.edu/courses/course-v1:OCW+18.031+2019_Spring/about
  weight: 1000
